commann code on the worksheet in RL

In [160]:
# all common on the setup in modules
import gymnasium as gym
import numpy as np

env = gym.make("CartPole-v1")
state, info = env.reset()
gamma = 0.99

In [161]:
#1 Sequential decision process
trajectories = []

In [162]:
#2 MDP components
S = env.observation_space
A = env.action_space

A,S

(Discrete(2),
 Box([-4.8               -inf -0.41887903        -inf], [4.8               inf 0.41887903        inf], (4,), float32))

In [163]:
#3 Markov property (depends only on current state)
action = A.sample()
next_state, reward, terminated, trucated, info = env.step(action)
action

1

In [164]:
#4 State representation
state

array([-0.03858292, -0.00603979,  0.00146659, -0.0433813 ], dtype=float32)

In [165]:
# 5 Real-world MDP example (cart-pole environment)
env

<TimeLimit<OrderEnforcing<PassiveEnvChecker<CartPoleEnv<CartPole-v1>>>>>

In [166]:
#6 State vs observation
observation = state
print(observation)
print(state)

[-0.03858292 -0.00603979  0.00146659 -0.0433813 ]
[-0.03858292 -0.00603979  0.00146659 -0.0433813 ]


In [167]:
# 7 Action definition
action = A.sample()
action

1

In [168]:
#8 Transition probability (implicit in env)
transition = (state, action, reward, next_state)
transition

(array([-0.03858292, -0.00603979,  0.00146659, -0.0433813 ], dtype=float32),
 1,
 1.0,
 array([-0.03870372,  0.1890611 ,  0.00059896, -0.33560115], dtype=float32))

In [169]:
#9 Stochastic transition (noise effect)
state = [env.step(A.sample())[0] for _ in range(5)]
state

[array([-0.0349225 ,  0.38417453, -0.00611306, -0.62809515], dtype=float32),
 array([-0.02723901,  0.18913841, -0.01867496, -0.33734366], dtype=float32),
 array([-0.02345624,  0.38452107, -0.02542184, -0.6358567 ], dtype=float32),
 array([-0.01576582,  0.18976274, -0.03813897, -0.35128677], dtype=float32),
 array([-0.01197056,  0.38540572, -0.0451647 , -0.65574795], dtype=float32)]

In [170]:
#10 reward function
reward

1.0

In [171]:
#11 Negative reward example
penalty = -10
penalty

-10

In [172]:
#12 Policy definition
def policy(S):
    return A.sample()

policy(S)

1

In [173]:
#13 Deterministic policy
def deterministic_policy(S):
    return 0
deterministic_policy(S)

0

In [174]:
# 14 Stochastic policy
def stochastic_policy(S):
    return np.random.choice([0,1],p=[0.7, 0.3])
stochastic_policy(S)

0

In [175]:
#15 Return calculation
returns = []
G = 0
for t in range(5):
    G += (gamma ** t) * reward
    returns.append(G)
    
returns

[1.0, 1.99, 2.9701, 3.940399, 4.90099501]

In [176]:
#16 Discount factor usage
discounted_rewards = reward * gamma
discounted_rewards

0.99

In [ ]:
#17 